// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrailsApi.Models;

namespace Business.Migrations
{
    [DbContext(typeof(TrailsApiContext))]
    [Migration("20220913184111_ChangeCoordinatesDataTypeAndUpdateModelProps")]
    partial class ChangeCoordinatesDataTypeAndUpdateModelProps
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TrailsApi.Models.TrailMarker", b =>
                {
                    b.Property<int>("TrailMarkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("isLandmark")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isTrailhead")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("TrailMarkerId");

                    b.ToTable("TrailMarkers");

                    b.HasData(
                        new
                        {
                            TrailMarkerId = 1,
                            Description = "dirt trail off of Springwater",
                            Latitude = 45.490696,
                            Longitude = -122.49699200000001,
                            Name = "Powell Butte Trailhead",
                            isLandmark = false,
                            isTrailhead = true
                        },
                        new
                        {
                            TrailMarkerId = 2,
                            Description = "pond that seasonally has many frogs and frogs sounds",
                            Latitude = 45.485812000000003,
                            Longitude = -122.649976,
                            Name = "Oaks Bottom Frog Pond",
                            isLandmark = true,
                            isTrailhead = false
                        },
                        new
                        {
                            TrailMarkerId = 3,
                            Description = "when you arrive to the lighthouse you have reached end of the trail! Enjoy!",
                            Latitude = 45.848579999999998,
                            Longitude = -122.78834999999999,
                            Name = "Sauvies Island Lighthouse",
                            isLandmark = true,
                            isTrailhead = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
